### ISSUE TITLE
Zmienić mapowanie komend na zwykłą listę

### ISSUE THREAD

**Issue by grzegorz2047** [grzegorz2047/OpenGuild#142]
Dodać do command getAliases() i używać contains w wyszukiwaniu danego argumentu komendy.

**Comment by TheMolkaPL** [comment]
Jeżeli rozumiem to chcesz loopować wszystkie zarejestrowane komendy i w każdej sprawdzać czy jej nazwa lub alias jest równy podanej komendzie. Będzie to mniej optymalnie niż indeksowanie wszystkich komend po nazwie i aliasie w mapie.

**Comment by grzegorz2047** [comment]
@TheMolkaPL Generalnie moja poprawka jest podobnie wydajnościowo, bo zamieniłem fora na contains.
Dodatkowo dałem breaki, żeby dalej nie "szukać" komendy.
No na pewno będzie wydajniej niż obecnie. Chyba 🗡

**Comment by TheMolkaPL** [comment]
To tak, ale lepiej byłoby to zrobić jako mapę, gdzie kluczem jest string - nazwa i wszystkie aliasy, oraz wartość obiekt komendy. Przy wykonywaniu komendy pobierałoby się jedynie wartość z mapy.

**Comment by grzegorz2047** [comment]
Jedyna maksymalizacja wydajności to zrobienie dla każdego aliasu podpiąć komendę, dzięki czemu po podaniu aliasu jako klucza, zwraca nam obiekt komendy, przez co w najlepszym wypadku złożoność to 0(1). Ale już mi się nie chce dalej tego poprawiać, Bo i tak działa to dosyć sprawnie.
